{
 "title": "KNMI Weerstations",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Stations", "label": "KNMI", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "Temperatuur",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperatuur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "T" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Grondtemperatuur (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "T10N" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luchtdruk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "Luchtdruk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Neerslag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "Neerslag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "query": "SELECT max(\"RH\")  / 10 FROM /^$Stations$/ WHERE (\"RH\" > -1) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RH" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "RH", "operator": ">", "value": "-1" }
     ]
    },
    {
     "alias": "< 0.05 mm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "query": "SELECT max(\"RH\") *-0.05 FROM /^$Stations$/ WHERE (\"RH\" = '-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RH" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*-0.05" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "RH", "operator": "<", "value": "0" }
     ]
    },
    {
     "alias": "Sneeuw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"S\")*0  FROM /^$Stations$/ WHERE (\"S\" > 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Onweer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"O\")*-0.2  FROM /^$Stations$/ WHERE (\"O\" > 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Ijsvorming",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Y\")*-0.3  FROM /^$Stations$/ WHERE (\"Y\" > 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"M\")*-0.1  FROM /^$Stations$/ WHERE (\"M\" > 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luchtvochtigheid",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "Rel. luchtvochtigheid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "U" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Dauwpunt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "TD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Windrichting",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Windrichting  (90=O, 180=Z, 270=W ,360/1=N)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "DD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "DD", "operator": "<", "value": "361" },
      { "condition": "AND", "key": "DD", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Windstil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "DD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "DD", "operator": "<", "value": "1" }
     ]
    },
    {
     "alias": "Veranderlijk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "DD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "DD", "operator": ">", "value": "360" }
     ]
    }
   ]
  },
  {
   "title": "Windsnelheid",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "Windsnelheid (gem)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "FH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10 * 3.6" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Windstoten (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "FX" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10 * 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zicht",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "< 5km",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "query": "SELECT (mean(\"VV\") +1)*100 FROM /^$Stations$/ WHERE (\"VV\" < 51) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "VV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "VV", "operator": "<", "value": "49" }
     ]
    },
    {
     "alias": "> 5km",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "query": "SELECT (mean(\"VV\") -50)*1000  FROM /^$Stations$/ WHERE (\"VV\" > 50) AND (\"VV\" < 80) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "VV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "VV", "operator": "<", "value": "49" }
     ]
    },
    {
     "alias": "> 35km",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "query": "SELECT ((mean(\"VV\")-80)*5+35)*1000  FROM /^$Stations$/ WHERE (\"VV\" > 79) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "VV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "VV", "operator": "<", "value": "49" }
     ]
    },
    {
     "alias": "Mist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"M\")-1  FROM /^$Stations$/ WHERE (\"M\" > 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bewolking",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Dekkingsgraad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "N" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "N", "operator": "<", "value": "9" }
     ]
    },
    {
     "alias": "Bovenlucht onzichtbaar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "N" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/9" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "N", "operator": ">", "value": "8" }
     ]
    }
   ]
  },
  {
   "title": "Globale straling",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "alias": "Straling",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Stations$/",
     "select": [
      [
       { "params": [ "Q" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*10000/3600" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}